name: nick_actions

on:
  schedule:
    - cron: '0,30 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Checkout my private repo
        uses: actions/checkout@v2
        env:
          SECRET_TOKEN: ${{ secrets.CREDENTIALS_TOKEN }}
          SECRET_REPO: ${{ secrets.SECRET_REPO }}
        with:
          repository: raynbowy23/${{ secrets.SECRET_REPO }}
          token: ${{ secrets.CREDENTIALS_TOKEN}}

      - name: Get nick's activity
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          WEATHER_API: ${{ secrets.WEATHERAPI}}
          NICK_API: ${{ secrets.NICKAPI }}
        run: |
          python /home/runner/work/nick_activity_analyzer/get_activity.py